apiVersion: apps/v1
kind: Deployment
metadata:
  name: WebOrderitem-deployment
  labels:
    app: WebOrderitem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: WebOrderitem
  template:
    metadata:
      labels:
        app: WebOrderitem
    spec:
      containers:
      - name: WebOrderitem
        image: WebOrderitem.azurecr.io/myapirepo:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: webapisecretkey
---
apiVersion: v1
kind: Service
metadata:
  name: WebOrderitemsvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: WebOrderitem